version = 1

[[annotations]]
path = ["README.md", "*/Dockerfile", "Jenkinsfile*", "Makefile", "server/compose.yaml", "server/docker.wrapper"]
precedence = "closest"
SPDX-FileCopyrightText = "Â© 2025 Clifford Weinmann <https://www.cliffordweinmann.com/>"
SPDX-License-Identifier = "MIT-0"
